### ISSUE TITLE
Please add mesh of case

### ISSUE THREAD

**Issue by danfinlay** [firefly/wallet#1]
I downloaded Sketchup, and tried exporting `.obj` files of the case, but when I do it, part of one of the sides seems to be non manifold, and so it's unprintable.

Could you also add some correctly meshed versions of the case, so they're ready to be 3D printed, without needing sketchup?

**Comment by ricmoo** [comment]
Yes, I will upload one tonight. It should be a manifold, but I’ll debug that too.

I can upload a slic3r too.

**Comment by danfinlay** [comment]
I think slicer gcode tends to be a little more printer-dependent, so really just a solid mesh is all I need. I have half of it printed fine (button half), just need the battery side.

(Can't wait to set it up!!)

**Comment by ricmoo** [comment]
Sorry. DevCon has been more time consuming than I expected. I will try to get to this tonight.

**Comment by danfinlay** [comment]
Sweet!

**Comment by ricmoo** [comment]
I have added the STL files. Let me know if they don't work for you.

I need to upgrade my version of SketchUp to the Pro version before I can export the OBJ files.

**Comment by danfinlay** [comment]
Looks good, thank you, printing now!
