### ISSUE TITLE
Help with Signatures

### ISSUE THREAD

**Issue by 0xCaFeBEef** [firefly/wallet#14]
Realize this is an old project, and also realize this was made for an Arduino, but having an issue with signing on Windows 10.

New to both C++ and Ethereum development, so bear with me if you would. This project of yours has been invaluable in learning both!

The signature doesn't appear to be valid after passing a proper hash and private key to it. The private key works with obtaining the public key, so pretty sure that's solid. The keccak hash appears to be working correctly as it returns an expected hash value. The signature does indeed return a value of a valid length, but it does not appear compatible with latest versions of signature validation.

Would you be willing to spend any additional time on this to help me through it? Thank you in advance!
[verifySig.txt](https://github.com/firefly/wallet/files/8918805/verifySig.txt)

**Comment by ricmoo** [comment]
The signature produced is non-normalized and the recoveryParam is not included; this can be calculated though easy enough in JavaScript using the elliptic library.

The new Firefly coming out soon has had micro-etc updated to normalize and include the recovery param, so that it is immediately usable by the Ethereum network.

**Comment by 0xCaFeBEef** [comment]
Thank you very much for your response, and am excited to hear about the new version!

**Comment by 0xSilkRoad** [comment]
Hi @ricmoo, any update regarding the release for new Firefly?

**Comment by ricmoo** [comment]
Yes! Coming very soon! We are hoping to have some exciting news by EthCC. :)

I will be making the repo for the new firmware public soon too, which includes the updated crypto libs, that have normalized canonical signing too.
