### ISSUE TITLE
Source code for the wallet is missing

### ISSUE THREAD

**Issue by slegge** [firefly/wallet#2]
I bought a couple of the hardware wallet kits at ETHWaterloo and the instructions and source were supposed to be posted within days but they still aren't available.

**Comment by ricmoo** [comment]
Sorry, it's been taking longer than expected to get the source code ready. On the plane back from DevCon on Wednesday we got RFC6979 working, which was one of the big bullet points we wanted finished before releasing. This means we don't need to rely on a RNG on device for signing, so it is much more secure.

My partner has also finished most of the testing platform so we can send/receive the test suite (same test suite as ethers.js) to the device over serial one test case at a time.

I am updating Ethers Wallet for iOS 11 and iPhone X right now, and then I will publish the branch with Firefly v0.1 support.

We are hoping to get the initial version of the source code up very soon, along with the new 3D printed case which is easier to wire up than the v0 currently posted.

**Comment by maaft** [comment]
Any news regarding the source code? I'd love to jump in :)

**Comment by ricmoo** [comment]
The source code is now up.

Thanks! :)
