### ISSUE TITLE
Schematic and Breadboard diagrams show that CE is not connected but it needs to be

### ISSUE THREAD

**Issue by tricdc** [firefly/wallet#4]

**Comment by ricmoo** [comment]
If CE is left floating, the nRF24L01+ will remain in receive mode. We could add a pull-up resistor to make sure, if it was a concern.

If we connect the CE pin to the Arduino, it will enable us to use certain power-saving stand-by modes, but also means the Firefly could theoretically broadcast.

By leaving it floating or using a pull up resistor, we ensure the chip is hard-wired into receive-only mode.

**Comment by tricdc** [comment]
Oh, yeah sorry, i disconnected it yesterday and it wouldn't receive
transactions, but it works now
